import type { Conversation } from "./types";

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_1",
    status: "new",
    autopilotActive: false,
    unreadCount: 2,
    lead: {
      id: "l1",
      name: "María Santos",
      company: "Grupo Inversión Lima",
      title: "Directora de Operaciones",
      email: "m.santos@grupoinversion.com",
      phone: "+51 987 654 321",
      linkedinUrl: "https://www.linkedin.com/in/mariasantos",
      source: "linkedin",
      pipeline: "en_contacto",
      tags: [{ label: "SQL - Calificado", color: "bg-green-100 text-green-700" }, { label: "Enterprise", color: "bg-indigo-100 text-indigo-700" }],
      value: 15000,
      notes: "Muy interesada en la funcionalidad de CRM. Tiene reunión con su equipo el lunes.",
      createdAt: "2026-05-23",
    },
    messages: [
      { id: "m1", sender: "ai",   text: "Hola María, vi que lideras operaciones en Grupo Inversión — me gustaría conectar y compartirte algo que podría optimizar su proceso de prospección comercial.",           timestamp: "2026-05-23T09:00:00Z", read: true  },
      { id: "m2", sender: "lead", text: "Hola! Claro, cuéntame más. ¿De qué se trata?",                                                                                                                             timestamp: "2026-05-23T11:30:00Z", read: true  },
      { id: "m3", sender: "ai",   text: "NexusAI automatiza la prospección en LinkedIn: extrae leads, genera mensajes personalizados con IA y gestiona el pipeline. ¿Tienes 20 minutos esta semana para una demo?", timestamp: "2026-05-23T12:00:00Z", read: true  },
      { id: "m4", sender: "lead", text: "Suena interesante. ¿Tienen integración con CRMs como HubSpot o Salesforce?",                                                                                               timestamp: "2026-05-27T14:20:00Z", read: false },
      { id: "m5", sender: "lead", text: "Y también me gustaría saber el precio antes de la demo.",                                                                                                                   timestamp: "2026-05-27T14:21:00Z", read: false },
    ],
    aiSuggestions: [
      { id: "s1", text: "¡Hola María! Sí, tenemos integración nativa con HubSpot y Salesforce via API. En cuanto al precio, nuestro plan PRO parte desde $199/mes. ¿Te va bien el jueves a las 3pm para la demo?", intent: "schedule" },
      { id: "s2", text: "Buena pregunta! Integramos con HubSpot, Salesforce y Pipedrive. El precio depende del plan — ¿puedes contarme cuántos SDRs tiene tu equipo para darte una propuesta exacta?", intent: "qualify"  },
      { id: "s3", text: "Tenemos integraciones con los principales CRMs. Te envío nuestra hoja de precios por aquí para que lo revises antes de la demo. ¿Cuándo tienes disponibilidad esta semana?", intent: "follow_up" },
    ],
  },
  {
    id: "conv_2",
    status: "ai_handling",
    autopilotActive: true,
    unreadCount: 0,
    lead: {
      id: "l2",
      name: "Roberto Díaz",
      company: "Startup Fintech SA",
      title: "CEO & Co-founder",
      email: "r.diaz@fintechsa.pe",
      phone: "+51 987 654 000",
      linkedinUrl: "https://www.linkedin.com/in/robertodiaz",
      source: "linkedin",
      pipeline: "demo_agendada",
      tags: [{ label: "SQL - Hot Lead", color: "bg-red-100 text-red-700" }, { label: "Fintech", color: "bg-sky-100 text-sky-700" }],
      value: 22000,
      notes: "CEO muy activo en LinkedIn. Tiene un equipo de 5 SDRs. Demo confirmada para el viernes.",
      createdAt: "2026-05-20",
    },
    messages: [
      { id: "m1", sender: "ai",   text: "Roberto, vi tu perfil y el trabajo que están haciendo en Fintech SA — la tracción es impresionante. ¿Te interesaría ver cómo NexusAI puede escalar su prospección?",       timestamp: "2026-05-20T08:00:00Z", read: true },
      { id: "m2", sender: "lead", text: "Hola! Sí, estamos buscando exactamente algo así. ¿Cuándo podemos hablar?",                                                                                                   timestamp: "2026-05-20T10:00:00Z", read: true },
      { id: "m3", sender: "ai",   text: "Perfecto. Te agendo una demo para el viernes 30 de mayo a las 3pm. Te envío el link de Calendly.",                                                                           timestamp: "2026-05-20T10:30:00Z", read: true },
      { id: "m4", sender: "lead", text: "Confirmado. ¿Incluye la parte de automatización de mensajes con IA?",                                                                                                        timestamp: "2026-05-21T09:00:00Z", read: true },
      { id: "m5", sender: "ai",   text: "Sí, esa es la parte más potente. Claude 3.5 genera mensajes ultra-personalizados basados en el perfil del lead. Te haré una demo completa de ese módulo.",                  timestamp: "2026-05-21T09:15:00Z", read: true },
      { id: "m6", sender: "lead", text: "Excelente. Nos vemos el viernes entonces. 👍",                                                                                                                               timestamp: "2026-05-21T09:20:00Z", read: true },
    ],
    aiSuggestions: [
      { id: "s1", text: "Roberto, confirmando nuestra demo del viernes 30/05 a las 3pm. Te envío el link: calendly.com/nexusai/demo. ¿Algo específico que quieras ver?", intent: "schedule"   },
      { id: "s2", text: "¡Nos vemos el viernes! Para aprovechar mejor el tiempo, ¿puedes contarme cuántos prospectos por mes maneja tu equipo actualmente?",             intent: "qualify"    },
      { id: "s3", text: "Perfecto Roberto. Te mando un recordatorio el día anterior. Si necesitas reagendar, avísame sin problema.",                                       intent: "follow_up"  },
    ],
  },
  {
    id: "conv_3",
    status: "human",
    autopilotActive: false,
    unreadCount: 1,
    lead: {
      id: "l3",
      name: "Ana García",
      company: "Corporación Digital SAC",
      title: "VP de Ventas",
      email: "a.garcia@corpdigital.com",
      linkedinUrl: "https://www.linkedin.com/in/anagarcia",
      source: "email",
      pipeline: "propuesta",
      tags: [{ label: "Enterprise", color: "bg-indigo-100 text-indigo-700" }, { label: "CRM + Campañas", color: "bg-violet-100 text-violet-700" }],
      value: 35000,
      notes: "Revisando la propuesta con su equipo financiero. Decisión en 2 semanas.",
      createdAt: "2026-05-18",
    },
    messages: [
      { id: "m1", sender: "user", text: "Hola Ana, te envío la propuesta comercial que acordamos. Incluye los 3 planes y el descuento por pago anual.",                                                               timestamp: "2026-05-25T10:00:00Z", read: true  },
      { id: "m2", sender: "lead", text: "Gracias. Lo revisaré con mi equipo esta semana. Una pregunta: ¿el plan Enterprise incluye workspaces multi-usuario?",                                                        timestamp: "2026-05-25T15:00:00Z", read: true  },
      { id: "m3", sender: "user", text: "Sí, el plan Enterprise incluye workspaces ilimitados con roles y permisos granulares. Puedes ver la demo de esa funcionalidad en el video que adjunté en la propuesta.",    timestamp: "2026-05-26T09:00:00Z", read: true  },
      { id: "m4", sender: "lead", text: "Perfecto. Tengo una última duda sobre el SLA de soporte. ¿Tienen SLA de respuesta garantizado?",                                                                             timestamp: "2026-05-29T11:00:00Z", read: false },
    ],
    aiSuggestions: [
      { id: "s1", text: "¡Hola Ana! Sí, el plan Enterprise incluye SLA de respuesta en menos de 2 horas por chat en vivo + soporte dedicado. ¿Esto resuelve la duda? ¿Tienen fecha tentativa para la decisión?", intent: "close"     },
      { id: "s2", text: "Ana, nuestro SLA Enterprise garantiza respuesta en < 2h los días hábiles + account manager dedicado. ¿Cuándo podríamos cerrar esto?",                                                     intent: "close"     },
      { id: "s3", text: "¡Buena pregunta! El SLA de Enterprise es: 2h para temas críticos, 24h para el resto. También incluyes onboarding dedicado de 4 sesiones. ¿Tienes el visto bueno del equipo financiero?", intent: "qualify"   },
    ],
  },
  {
    id: "conv_4",
    status: "active",
    autopilotActive: false,
    unreadCount: 0,
    lead: {
      id: "l4",
      name: "Carlos Mendoza",
      company: "TechVision Perú",
      title: "Director de IT",
      email: "c.mendoza@techvision.pe",
      linkedinUrl: "https://www.linkedin.com/in/carlosmendoza",
      source: "linkedin",
      pipeline: "leads_entrantes",
      tags: [{ label: "IQL - Interesado", color: "bg-blue-100 text-blue-700" }, { label: "SaaS", color: "bg-violet-100 text-violet-700" }],
      value: 8500,
      notes: "Respondió al mensaje inicial. Parece receptivo pero aún no calificado.",
      createdAt: "2026-05-25",
    },
    messages: [
      { id: "m1", sender: "ai",   text: "Carlos, vi que lideras IT en TechVision — me gustaría conectar y compartirte cómo automatizamos la prospección B2B con IA.",    timestamp: "2026-05-25T09:00:00Z", read: true },
      { id: "m2", sender: "lead", text: "Hola! Gracias por conectar. ¿De qué se trata exactamente?",                                                                     timestamp: "2026-05-26T10:00:00Z", read: true },
      { id: "m3", sender: "user", text: "NexusAI extrae leads de LinkedIn y genera mensajes personalizados con IA. ¿Manejas prospección actualmente en TechVision?",     timestamp: "2026-05-26T10:30:00Z", read: true },
    ],
    aiSuggestions: [
      { id: "s1", text: "Carlos, solo quería hacer seguimiento — ¿tuviste oportunidad de revisar mi mensaje anterior? Estaré feliz de mostrarte una demo rápida.",        intent: "follow_up" },
      { id: "s2", text: "¿Cuántos SDRs tiene tu equipo actualmente? Dependiendo del volumen, NexusAI puede multiplicar su capacidad de prospección 5x.",                  intent: "qualify"   },
      { id: "s3", text: "Carlos, tenemos un caso de estudio de una empresa similar de IT en Lima que pasó de 20 a 120 demos/mes con NexusAI. ¿Te lo comparto?",           intent: "value_prop"},
    ],
  },
  {
    id: "conv_5",
    status: "new",
    autopilotActive: false,
    unreadCount: 1,
    lead: {
      id: "l5",
      name: "Luis Torres",
      company: "LogiTech Distribución",
      title: "Gerente Comercial",
      phone: "+51 999 123 456",
      linkedinUrl: "https://www.linkedin.com/in/luistorres",
      source: "linkedin",
      pipeline: "leads_entrantes",
      tags: [{ label: "IQL - Frío", color: "bg-zinc-100 text-zinc-600" }],
      value: 6200,
      notes: "Aceptó la conexión pero no ha respondido aún.",
      createdAt: "2026-05-27",
    },
    messages: [
      { id: "m1", sender: "ai",   text: "Luis, vi tu perfil y el trabajo que hace LogiTech en distribución. Creo que NexusAI puede ayudarles a escalar su equipo comercial. ¿Tienes 5 minutos para una llamada?", timestamp: "2026-05-27T09:00:00Z", read: true  },
      { id: "m2", sender: "lead", text: "Hola! Sí, puedo hablar. ¿De qué empresa eres exactamente?",                                                                                                                  timestamp: "2026-05-29T08:00:00Z", read: false },
    ],
    aiSuggestions: [
      { id: "s1", text: "¡Hola Luis! Soy de NexusAI — automatizamos la prospección B2B con IA. ¿Cuándo tienes 20 minutos para una demo? Puedo mostrarte exactamente cómo funciona.", intent: "schedule"  },
      { id: "s2", text: "Hola Luis! NexusAI es una plataforma que automatiza LinkedIn para equipos de ventas. En 20 minutos te puedo mostrar cómo duplicar tus leads cualificados. ¿Cuándo te viene bien?", intent: "schedule" },
      { id: "s3", text: "¡Claro! NexusAI ayuda a empresas como LogiTech a prospectar en LinkedIn de forma automática con IA. ¿Tienes disponibilidad esta semana para una llamada corta?", intent: "qualify" },
    ],
  },
];
